### ISSUE TITLE
Keyboard and Mouse Actions on Simulink (Mac OS)

### ISSUE THREAD

**Issue by jeljaik** [robotology-playground/WBI-Toolbox#108]
For anyone wondering about shortcuts on Mac Os (e.g. @DanielePucci) 

Full table [here](http://it.mathworks.com/help/simulink/ug/summary-of-mouse-and-keyboard-actions.html?refresh=true)

<img width="467" alt="screen shot 2015-11-10 at 11 24 52 am" src="https://cloud.githubusercontent.com/assets/5030039/11060021/b81df532-879d-11e5-8f2a-f10187e07972.png">

**Comment by DanielePucci** [comment]
:+1:
