### ISSUE TITLE
Add warning if this repository is deprecated

### ISSUE THREAD

**Issue by fiorisi** [robotology-playground/WBI-Toolbox#114]

**Comment by diegoferigo** [comment]
@traversaro Should we move this repo to https://github.com/robotology-legacy?

**Comment by traversaro** [comment]
I think it makes sense.

**Comment by diegoferigo** [comment]
@traversaro I don't have the rights for this operation. Do you have them?

**Comment by traversaro** [comment]
I gave you permissions.

**Comment by traversaro** [comment]
Done in https://github.com/robotology-playground/WBI-Toolbox/commit/6d5b5f7867e29611e6fe2ae0307b683c0054ce56 .
