### ISSUE TITLE
Investigate setJointBoundMax error (warning?)

### ISSUE THREAD

**Issue by jeljaik** [robotology-playground/WBI-Toolbox#13]
When using the method `bool getJointLimits(double *qMin, double *qMax, int joint=-1)` from wholeBodyModel I get the following error message:
`setJointBoundMax error: input vector has size 0 while should have size 32`

However the method returns just fine. Investigate why I keep getting this message and whether it's an actual error or just a warning. 

Mabye @traversaro can give me a hint.

**Comment by traversaro** [comment]
Fixed with the new_wbi_ID merge.

**Comment by jeljaik** [comment]
:cool: Thanks
