### ISSUE TITLE
Error running controllers

### ISSUE THREAD

**Issue by MoritzN89** [robotology-playground/WBI-Toolbox#33]
Hi,
I have tried to start e.g. the balancingControllerV2 in Simulink but got an assertion error because of jointLimites and this error message:
setJointBoundMin error: input vector has size 0 while should have size 32
so the controller doesent work and nothing happens in Gazebo.
I have updated everything and tried icub_fixed but the same error. I am using Matlab R2013a and Ubuntu 14.04 64 Bit.

I would be very thankful for help!

Greetings,
Moritz

**Comment by DanielePucci** [comment]
See 
https://github.com/robotology-playground/WBI-Toolbox/issues/57#issuecomment-73134333
