### ISSUE TITLE
Add an option to use a configuration file for yarpWholeBodyInterface different from the default

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/WBI-Toolbox#40]
Now the WBI-Toolbox is loading by default the `yarpWholeBodyInterface.ini` configuration file. 
It would make sense to add the option to load also configuration file for the yarpWholeBodyInterface with a different name. In all the modules of the codyco-modules we use the `wbi_conf_file` option to specify the name of the configuration file for the yarpWholeBodyInterface. 

cc @DanielePucci @francesco-romano

**Comment by jeljaik** [comment]
Fixed in https://github.com/robotology-playground/WBI-Toolbox/commit/8b52ca33c4a2e629a4f030197276d8903f409975
