### ISSUE TITLE
Jacobians seem to be wrong at WBIToolbox level, but not at C++ level

### ISSUE THREAD

**Issue by DanielePucci** [robotology-playground/WBI-Toolbox#48]
When I plot the jacobians of left and right foot, I expect a 3x3 identity matrix at top-left. As a consequence, the first three rows of the jacobians should not be identically zero. Instead, I get the following
![screenshot from 2014-12-30 11 53 17](https://cloud.githubusercontent.com/assets/5045846/5577849/8302fc56-901a-11e4-8914-3c0c08bd94d1.png)
![screenshot from 2014-12-30 11 53 33](https://cloud.githubusercontent.com/assets/5045846/5577850/830949c6-901a-11e4-9c53-630bec56ad15.png)
 
On the other hand, by adding a cout in wbInterface.cpp just after the jacobian is evaluated, i.e. 
![screenshot from 2014-12-30 11 54 56](https://cloud.githubusercontent.com/assets/5045846/5577860/c9ab40c8-901a-11e4-801e-b3eb4328e61c.png)

i get the expected values, 

![screenshot from 2014-12-30 11 57 33](https://cloud.githubusercontent.com/assets/5045846/5577881/13768a82-901b-11e4-896f-13002036842c.png)

You can see in issue #46 that @jeljaik gets the same fishy values.

**Comment by DanielePucci** [comment]
The shape seems correct, but it is difficult to check the numbers. What was the value of icub_fixed? If it was false, you should get similar results I got (see the picture above).

**Comment by traversaro** [comment]
We fixed this @jeljaik @francesco-romano  ?

**Comment by jeljaik** [comment]
Addressed in https://github.com/robotology-playground/WBI-Toolbox/commit/3ecd6de47a3633e27f69b9000fa154deb8f184eb
