### ISSUE TITLE
Joint Torques return 0

### ISSUE THREAD

**Issue by robertocalandra** [robotology-playground/WBI-Toolbox#52]
Trying to read the joint torques, even during a movement, always return 0. 
I tested by generating movements in both position and torque control, and neither works.

**Comment by traversaro** [comment]
Are you running the wholeBodyDynamics module?

**Comment by robertocalandra** [comment]
Separately on the yarpManager? No.
Is it required?

**Comment by traversaro** [comment]
Yes, basically the wholeBodyDynamics module is required to estimated the joint torques, you should find it in the robotStartup application in your yarpManager.

For more information in the force control, please check http://wiki.icub.org/wiki/Force_Control . It is a bit outdated (we will update it soon) but it explains the concepts quite well.

**Comment by robertocalandra** [comment]
Ok thank you. In that case, if i understand correctly when reading the Joint Torques block there is quite a bit of processing (e.g., estimation of external forces). Is it possible to directly access the low level readings from the joint torque sensors?

**Comment by traversaro** [comment]
As far as I know, `iCubDarmstad01` is measuring the joint torques through the 6 6-axis FT sensors embedded in the iCub body. You can access this sensors directly using the /icub/deviceId/analog:o port, where deviceId is one of the following `left_arm`,`right_arm`,`left_leg`,`right_leg`, `left_foot`, `right_foot`.

**Comment by jeljaik** [comment]
I will  assume that after launching `wholeBodyDynamicsTree` the block for retrieving joint torques was not returning 0 anymore. Therefore I proceed to close this issue. If this is  not the case, feel free to reopen :)

**Comment by robertocalandra** [comment]
Sorry, I lost track of this issue. Yes, using the wholeBodyDynamicsTree solved the problem.

**Comment by jeljaik** [comment]
:+1:
