### ISSUE TITLE
Hand moving spontaneously

### ISSUE THREAD

**Issue by robertocalandra** [robotology-playground/WBI-Toolbox#54]
I am not sure if this ticket is depending from the WBI-toolbox or not (might be lower-level). 
But during a pause between two experiments (with the WBI toolbox), two fingers of the left hand of iCubDarmstadt01 moved spontaneously (from completely extended to completely flexed).
This is quite awkward (and scary)... 
What should I try to log next time to diagnose the possible problem?

**Comment by DanielePucci** [comment]
Post this issue in 

https://github.com/robotology/QA/issues
