### ISSUE TITLE
Avoid warning when testing the WBI-Toolbox

### ISSUE THREAD

**Issue by iron76** [robotology-playground/WBI-Toolbox#65]
The COMPoseTesting which is suggested to test the WBI-Toolbox should be generated with an older version of Simulink. I am running the following version of matlab:

```
MATLAB Version: 8.0.0.783 (R2012b)
Operating System: Mac OS X  Version: 10.9.5 Build: 13F34 
```

and I getting this Warning (and a bunch of following others) which is annoying.
```
Warning: Loading model 'COMPoseTesting' generated with a newer  version (8.3) of Simulink
```

**Comment by jeljaik** [comment]
Fxed in https://github.com/robotology-playground/WBI-Toolbox/commit/abf3f3daa6230ee401222f4bf6fc3a0ba800f47c
