### ISSUE TITLE
Error when using the block: wholeBodyModel/Jacobians/Link Jacobian

### ISSUE THREAD

**Issue by iron76** [robotology-playground/WBI-Toolbox#87]
The installation seems to work fine in general but the block wholeBodyModel/Jacobians/Link Jacobian is giving me the following error:
```
Error in port widths or dimensions. Output port 1 of 'untitled/Link Jacobian/Link Jacobian' 
is a one dimensional vector with 186 elements.
```

**Comment by DanielePucci** [comment]
What is the value of ROBOT_DOF you set in the MATLAB workspace?

**Comment by iron76** [comment]
It was indeed wrong and not matching the supplied URDF.
