### ISSUE TITLE
problem with yRead block

### ISSUE THREAD

**Issue by azadm** [robotology-playground/WBI-Toolbox#94]
**Description:**
I get an error in Simulink after the last update today:
````
Error reported by S-function 'yRead' in 'controller/Subsystem/Subsystem/yarp read':
ERROR connecting ports!
````
and this is the error in Matlab command window:
````
WBI-Toolbox failed connecting /y2coordinator/qdes:o to /tmp/port/1 
````
and this is a part of message in the terminal that Matlab is running which I think is related to the problem:
````
yarp: Port /model/right_arm/rpc:o active at tcp://147.188.200.113:10087
yarp: Port /model/right_arm/command:o active at tcp://147.188.200.113:10088
yarp: Port /model/right_arm/state:i active at tcp://147.188.200.113:10089
yarp: Port /model/right_arm/stateExt:i active at tcp://147.188.200.113:10090
yarp: Sending output from /model/right_arm/rpc:o to /icubGazeboSim/right_arm/rpc:i using tcp
yarp: could not open datagram socket
Problem connecting to /icubGazeboSim/right_arm/command:i, is the remote device available?
yarp: Receiving input from /icubGazeboSim/right_arm/state:o to /model/right_arm/state:i using udp
yarp: Receiving input from /icubGazeboSim/right_arm/stateExt:o to /model/right_arm/stateExt:i using udp
yarp: Removing output from /model/right_arm/rpc:o to /icubGazeboSim/right_arm/rpc:i
yarp: Removing input from /icubGazeboSim/right_arm/state:o to /model/right_arm/state:i
yarp: Removing input from /icubGazeboSim/right_arm/stateExt:o to /model/right_arm/stateExt:i
yarpdev: ***ERROR*** driver <remote_controlboard> was found but could not open
[ERROR]Problems instantiating the device driver right_arm
[INFO][mdlStart] Succesfully exited robotConfig.
[INFO][robotStatus::robotInit] Finished robotInit
[INFO][mdlStart] Succesfully exited robotInit.
[INFO][mdlStart] FINISHED

[INFO][mdlStart] I AM GETTING UPDATED!!! 
YARP NETWORK INITIALIZED
YARP is running!!

yarp: Port /tmp/port/1 active at tcp://147.188.200.113:10139
[From] Port name will be: /y2coordinator/qdes:o
[To] Port name will be:   /tmp/port/1
Blocking? : 0
Timestamp? : 0
Autoconnect? : 1
Connecting '/y2coordinator/qdes:o' to '/tmp/port/1' 
[INFO][mdlTerminate] Inside robot object 0x7fff1c6bfc00 
[INFO][mdlTerminate] ctrl mode set
[INFO][robotStatus::~robotStatus] wbInterface in destructor: 0x7fff0e361190 
````

_____

**Further Information**:
- *System Information:* `Darwin dynamic200-113.cs.bham.ac.uk 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64`
- *Working branch:* `master`
- *Current commit:* `93601ad72996a04168ec4724973a573311c18ac8`
- *YARP ROOT:* `/Users/azadm/Documents/yarp`
- *ICUB_ROOT:* `/Users/azadm/Documents/icub-main`
- *YARP_DATA_DIRS:* `/Users/azadm/Documents/yarp/build/share/yarp:/Users/azadm/Documents/icub-main/build/share/iCub:/Users/azadm/Documents/codyco-superbuild/build/install/share/codyco:/Users/azadm/Documents/codyco-superbuild/build/install/share/codyco`
- *YARP_ROBOT_NAME:* `icubGazeboSim`
- *Yarp Installation:* `/Users/azadm/Documents/yarp/build/bin/Release/yarpserver`
- *LD_LIBRARY_PATH:*`:/Users/azadm/Documents/codyco-superbuild/build/install/lib`
- *LD_PRELOAD:*``
- *DYLD_INSERT_LIBRARIES:*``

**Comment by francesco-romano** [comment]
Any news on this?
If this still apply, please open reopen the issue.
